# pull official base image
FROM python:3.12-slim

# create directory for the app user
RUN mkdir -p /home/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_VIRTUALENVS_CREATE=False

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/app
RUN mkdir $APP_HOME/core
RUN mkdir $APP_HOME/apis
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME

# install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    libpq-dev \
    # unixodbc-dev \
    # msodbcsql17 \
    # apt-transport-https \
    vim \
    tzdata \
    pkg-config \
    netcat-traditional && \
    rm -rf /var/lib/apt/lists/*

# for sql server
# Add Microsoft’s APT repository for ODBC driver
# RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
# && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-prod.list \
# && apt-get update

# Install the Microsoft ODBC Driver 17 for SQL Server
# RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

# install dependencies
RUN pip install -U pip poetry && \
    rm -rf /root/.cache/pip
COPY poetry.lock pyproject.toml ./
RUN poetry install

# copy project
COPY . $APP_HOME
