# Generated by Django 6.1 on 2026-09-08 22:23

import core.managers
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepDefinition',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workflow_step_definition',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.IntegerField(db_index=True, default=3)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('token_version', models.UUIDField(default=uuid.uuid4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', core.managers.SoftDeleteUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_backend', models.IntegerField(default=1)),
                ('storage_key', models.CharField(max_length=1000, unique=True)),
                ('extension', models.CharField(blank=True, max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_object',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='core.fileobject'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('notify_type', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_bbox', models.JSONField(blank=True, default=dict)),
                ('detected_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parts', to=settings.AUTH_USER_MODEL)),
                ('preview_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_previews', to='core.fileobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PartStep',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.part')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_part_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part_step',
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=500)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='core.fileobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_source_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_source_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_document',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.sourcedocument'),
        ),
        migrations.CreateModel(
            name='StepRevision',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('revision_type', models.IntegerField(db_index=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('settings_schema_version', models.PositiveIntegerField(default=1)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('settings_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_step_revisions', to=settings.AUTH_USER_MODEL)),
                ('parent_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_revisions', to='core.steprevision')),
                ('part_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.partstep')),
            ],
            options={
                'db_table': 'step_revision',
                'ordering': ['-revision_no'],
            },
        ),
        migrations.CreateModel(
            name='RevisionArtifact',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_artifacts', to='core.fileobject')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.steprevision')),
            ],
            options={
                'db_table': 'revision_artifact',
                'ordering': ['role', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='partstep',
            name='latest_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.steprevision'),
        ),
        migrations.AddField(
            model_name='partstep',
            name='official_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.steprevision'),
        ),
        migrations.AddField(
            model_name='partstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_steps', to='core.workflowstepdefinition'),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_item',
            },
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='core.workitem'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['sha256', 'size_bytes'], name='idx_file_sha_size'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['source_document', 'status'], name='idx_part_source_status'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('source_document', 'sequence'), name='uq_source_part_sequence'),
        ),
        migrations.AddIndex(
            model_name='steprevision',
            index=models.Index(fields=['part_step', '-created'], name='idx_revision_latest'),
        ),
        migrations.AddIndex(
            model_name='steprevision',
            index=models.Index(fields=['part_step', 'revision_type'], name='idx_revision_type'),
        ),
        migrations.AddConstraint(
            model_name='steprevision',
            constraint=models.UniqueConstraint(fields=('part_step', 'revision_no'), name='uq_partstep_revision_no'),
        ),
        migrations.AddIndex(
            model_name='revisionartifact',
            index=models.Index(fields=['revision', 'role'], name='idx_artifact_revision_role'),
        ),
        migrations.AddConstraint(
            model_name='revisionartifact',
            constraint=models.UniqueConstraint(fields=('revision', 'role', 'sequence'), name='uq_revision_artifact_sequence'),
        ),
        migrations.AddIndex(
            model_name='partstep',
            index=models.Index(fields=['part', 'status'], name='idx_partstep_part_status'),
        ),
        migrations.AddConstraint(
            model_name='partstep',
            constraint=models.UniqueConstraint(fields=('part', 'step'), name='uq_part_step'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status', '-created'], name='idx_workitem_status_created'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['work_item', 'status'], name='idx_source_workitem_status'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('work_item', 'sequence'), name='uq_workitem_source_sequence'),
        ),
    ]
