# Generated by Django 6.1 on 2026-09-08 22:39

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workflow_template',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='settings_schema_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workitem',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='core.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='TemplateStep',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('settings_schema_version', models.PositiveIntegerField(default=1)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_steps', to='core.workflowstepdefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_steps', to='core.workflowtemplate')),
            ],
            options={
                'db_table': 'template_step',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('template', 'step'), name='uq_template_step'), models.UniqueConstraint(fields=('template', 'sequence'), name='uq_template_sequence')],
            },
        ),
    ]
